FROM python:3.9-slim

EXPOSE 5000

WORKDIR /app
COPY requirements.txt ./

RUN python3 -m venv venv
RUN . venv/bin/activate

RUN pip install -r requirements.txt
COPY main.py ./
CMD ["python", "main.py"]
